In [2]:
import numpy as np

In [31]:
l1 = np.array([2,3,4,5,10])
l2 = np.array([5])
l3 = np.array([2,5,11])
l4 = np.array(4)
l5 = np.array([[2,3,4,5,6],[1,2,34,56,1]])

In [33]:
l5.shape 

(2, 5)

### simple `+` on numpy arrays: 

In [34]:
all_ls = [l1,l2,l3,l4, l5 ]

In [41]:
for a1 in all_ls :
    for a2 in all_ls: 
        try:
            print "a1:",a1,"\na2:",a2, "\n sum a1+a2:\n",a1+a2 
        except Exception as e: 
            print e 
        print "--- "
        try: 
            print "a1:",a1,"\na2:",a2, "\n sum a2+a1:\n",a2+a1
            #print "a1:",a1,"a2:",a2, "sum a2+a1: ",a2+a1
        except Exception as e : 
            print e  
        print "--- "

a1: [ 2  3  4  5 10] 
a2: [ 2  3  4  5 10] 
 sum a1+a2:
[ 4  6  8 10 20]
--- 
a1: [ 2  3  4  5 10] 
a2: [ 2  3  4  5 10] 
 sum a2+a1:
[ 4  6  8 10 20]
--- 
a1: [ 2  3  4  5 10] 
a2: [5] 
 sum a1+a2:
[ 7  8  9 10 15]
--- 
a1: [ 2  3  4  5 10] 
a2: [5] 
 sum a2+a1:
[ 7  8  9 10 15]
--- 
a1: [ 2  3  4  5 10] 
a2: [ 2  5 11] 
 sum a1+a2:
operands could not be broadcast together with shapes (5,) (3,) 
--- 
a1: [ 2  3  4  5 10] 
a2: [ 2  5 11] 
 sum a2+a1:
operands could not be broadcast together with shapes (3,) (5,) 
--- 
a1: [ 2  3  4  5 10] 
a2: 4 
 sum a1+a2:
[ 6  7  8  9 14]
--- 
a1: [ 2  3  4  5 10] 
a2: 4 
 sum a2+a1:
[ 6  7  8  9 14]
--- 
a1: [ 2  3  4  5 10] 
a2: [[ 2  3  4  5  6]
 [ 1  2 34 56  1]] 
 sum a1+a2:
[[ 4  6  8 10 16]
 [ 3  5 38 61 11]]
--- 
a1: [ 2  3  4  5 10] 
a2: [[ 2  3  4  5  6]
 [ 1  2 34 56  1]] 
 sum a2+a1:
[[ 4  6  8 10 16]
 [ 3  5 38 61 11]]
--- 
a1: [5] 
a2: [ 2  3  4  5 10] 
 sum a1+a2:
[ 7  8  9 10 15]
--- 
a1: [5] 
a2: [ 2  3  4  5 10] 
 sum a2+a1:
[ 7  8

#### from above : 

* if one is of dim n-1 and other of dim n, and has length same as length of each element of the matrix( having larger dim), add to each element of array/ matrix  
* if equal-lengths  , do element wise addition 
* else throws error 

#### tying with matrix of dim 3 + dim 2 to confirm above: 

In [76]:
m3 = np.random.rand(3,4,5)

In [102]:
m2 = np.random.rand(4,1)
m2= np.ones([4,1])

In [112]:
m2 = np.asarray([ [1,2,3,4,6],[5,12,13,50,9] ,[0,12,14,2,14],[78,1,5,6,12] ])

In [113]:
m3+m2

array([[[ 1.84972489,  2.28702805,  3.4358031 ,  4.96019948,
          6.79397433],
        [ 5.58971861, 12.58846972, 13.18012893, 50.04505818,
          9.26833468],
        [ 0.72444199, 12.9041326 , 14.881998  ,  2.40379441,
         14.54198251],
        [78.91090152,  1.4063313 ,  5.47245381,  6.21906354,
         12.10063887]],

       [[ 1.85275965,  2.64799504,  3.44189271,  4.65425008,
          6.09584986],
        [ 5.83311956, 12.92066935, 13.55895847, 50.70768082,
          9.77972925],
        [ 0.39216178, 12.70921718, 14.28969084,  2.32982631,
         14.9502369 ],
        [78.22870309,  1.20975421,  5.7273663 ,  6.99715849,
         12.63259719]],

       [[ 1.20415971,  2.14790835,  3.11241362,  4.76040997,
          6.82113343],
        [ 5.10732813, 12.05565231, 13.656811  , 50.27504249,
          9.94407866],
        [ 0.94273988, 12.81275957, 14.11585612,  2.57095562,
         14.85214747],
        [78.23125448,  1.68820064,  5.81006576,  6.17438329,
         12

#### I can only add elements of shape n-1 with each element having size equal to inner elemet or the innermost shape being euqal to 1 

## Now coming to np.sum( )

In [116]:
a = np.asarray([1,2])
b = np.asarray([3,4])

In [119]:
print np.sum.func_doc


    Sum of array elements over a given axis.

    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.

        .. versionadded:: 1.7.0

        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In that case, if `a` is signed then the platform integer
        is used while if `a` is unsigned then an unsigned integer of the
        same precision

## params to check: 
--- 
* what happens with different values of axis.
* What happens with different values of keep_dims
* How is working different from the `+` op tested above. 
lets get started  :p  belowww. 

### dimensions and axis explained clearly [here](https://stackoverflow.com/questions/40857930/how-does-numpy-sum-with-axis-work) 

In [162]:
l1 = np.array([2,3,4,5,10])
l2 = np.array([5])
l3 = np.array([2,5,11])
l4 = np.array(4)
l5 = np.array([[2,3,4,5,6],[1,2,34,56,1]])
l6 = np.random.randint(-50,50, size =[3,4,5] )

In [164]:
all_ls = [l1,l2,l3,l4,l5,l6]

In [165]:
for ll in all_ls :
    print " for l= \n",ll
    print "dim of ll ",np.ndim(ll),", shape of ll ", ll.shape 
    print "regular:"
    print np.sum( ll )
    print np.sum( ll ).shape 
    print "axis 0 :"
    print np.sum( ll, axis = 0  )
    print np.sum( ll, axis = 0  ).shape 
    print "axis 1 :"
    try:
        print np.sum( ll, axis = 1  )
        print np.sum( ll, axis = 1  ).shape 
    except Exception as e : 
        print e 
    print "axis 2 :"
    try: 
        print np.sum( ll, axis = 2  )
        print np.sum( ll, axis = 2  ).shape 
    except Exception as e : 
        print e 
    print "======================================"

 for l= 
[ 2  3  4  5 10]
dim of ll  1 , shape of ll  (5,)
regular:
24
()
axis 0 :
24
()
axis 1 :
axis 1 is out of bounds for array of dimension 1
axis 2 :
axis 2 is out of bounds for array of dimension 1
 for l= 
[5]
dim of ll  1 , shape of ll  (1,)
regular:
5
()
axis 0 :
5
()
axis 1 :
axis 1 is out of bounds for array of dimension 1
axis 2 :
axis 2 is out of bounds for array of dimension 1
 for l= 
[ 2  5 11]
dim of ll  1 , shape of ll  (3,)
regular:
18
()
axis 0 :
18
()
axis 1 :
axis 1 is out of bounds for array of dimension 1
axis 2 :
axis 2 is out of bounds for array of dimension 1
 for l= 
4
dim of ll  0 , shape of ll  ()
regular:
4
()
axis 0 :
4
()
axis 1 :
axis 1 is out of bounds for array of dimension 0
axis 2 :
axis 2 is out of bounds for array of dimension 0
 for l= 
[[ 2  3  4  5  6]
 [ 1  2 34 56  1]]
dim of ll  2 , shape of ll  (2, 5)
regular:
114
()
axis 0 :
[ 3  5 38 61  7]
(5,)
axis 1 :
[20 94]
(2,)
axis 2 :
axis 2 is out of bounds for array of dimension 2
 for l= 
[[[

From above results: The axis along which sum takes place is dropped, If `original shape  = [s1,s2,s3,s4..s_n]` and sum along `axis = i` , then `new dim = [a1,a2,a3..] without s_i` 

##### study with l6: 

In [169]:
print l6

[[[-46 -25 -21  48  44]
  [ 16 -32  -2 -24  11]
  [-17  31 -20  35  25]
  [-24  27 -41  38  22]]

 [[-49  20  42  35  38]
  [-28  29  19  20 -44]
  [ -4 -36 -27  26 -18]
  [-15  -1  40  -9  32]]

 [[ 45  18 -11  25  26]
  [ 22   7  -7  15  24]
  [ 15 -18  41  30  17]
  [-25  40 -12 -17  17]]]


In [170]:
print l6.shape 
print np.ndim(l6)

(3, 4, 5)
3


In [173]:
print "regular sum: "
print np.sum(l6)

regular sum: 
367


In [176]:
print "axis 0 : drops axis 0 , new shape should be (4,5) "
print np.sum(l6, axis = 0 )
print np.sum(l6, axis = 0 ).shape 

axis 0 : drops axis 0 , new shape should be (4,5) 
[[-50  13  10 108 108]
 [ 10   4  10  11  -9]
 [ -6 -23  -6  91  24]
 [-64  66 -13  12  71]]
(4, 5)


In [177]:
print "axis 1 : drops axis 1 , new shape should be (3,5) "
print np.sum(l6, axis = 1 )
print np.sum(l6, axis = 1 ).shape 

axis 1 : drops axis 1 , new shape should be (3,5) 
[[-71   1 -84  97 102]
 [-96  12  74  72   8]
 [ 57  47  11  53  84]]
(3, 5)


In [180]:
print "axis 2 : drops axis 2 , new shape should be (3,4 ) "
print np.sum(l6, axis = 2 )
print np.sum(l6, axis = 2 ).shape 

axis 2 : drops axis 2 , new shape should be (3,4 ) 
[[  0 -31  54  22]
 [ 86  -4 -59  47]
 [103  61  85   3]]
(3, 4)


In [183]:
## Now testing keep-dims: 
print "axis 0 : drops axis 0"
print np.sum(l6, axis = 0, keepdims= True  )
print np.sum(l6, axis = 0, keepdims= True  ).shape 

axis 0 : drops axis 0
[[[-50  13  10 108 108]
  [ 10   4  10  11  -9]
  [ -6 -23  -6  91  24]
  [-64  66 -13  12  71]]]
(1, 4, 5)


In [182]:
## Now testing keep-dims: 
print "axis 1 : drops axis 1 "
print np.sum(l6, axis = 1, keepdims= True  )
print np.sum(l6, axis = 1, keepdims= True  ).shape 

axis 1 : drops axis 1 
[[[-71   1 -84  97 102]]

 [[-96  12  74  72   8]]

 [[ 57  47  11  53  84]]]
(3, 1, 5)


In [184]:
## Now testing keep-dims: 
print "axis 2 : drops axis 2 "
print np.sum(l6, axis = 2, keepdims= True  )
print np.sum(l6, axis = 2, keepdims= True  ).shape 

axis 2 : drops axis 2 
[[[  0]
  [-31]
  [ 54]
  [ 22]]

 [[ 86]
  [ -4]
  [-59]
  [ 47]]

 [[103]
  [ 61]
  [ 85]
  [  3]]]
(3, 4, 1)


The axis which was originall dropped becomes 1 when using `keep_dims  = True `